config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  resources :charges
  get '/', :to => 'welcome#index'
  post '/save_amount', to: 'charges#save_amount', as: 'save_amount'
  get '/api' => "api/v1/compaigns#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compaign.rb
class Compaign < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/compaigns_controller.rb
class Api::V1::CompaignsController < ApplicationController
    #skip_before_action :verify_authenticity_token

    def index
     return render :json => {:compaigns => Compaign.all}
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include Wicked::Wizard
  require "stripe"
  Stripe.api_key = ENV['STRIPE_SECRET_KEY']
  steps :take_amount, :take_card_info, :show_confirmation

  def show
    render_wizard
  end

  def save_amount 
    cookies[:amount] = params[:amount]
    redirect_to charge_path(:take_card_info)
  end

  def create
    begin
      stripe_params = {
        :name => params[:name],
        :description => cookies[:campaign].present? ? cookies[:campaign] : 'Basic',
        :email => params[:email],
        :source => params[:stripeToken],
        :phone => params[:phone]
      }
      customer = Stripe::Customer.create(stripe_params)
      rescue Stripe::CardError => e
        flash[:error] = e.message
      rescue Stripe::InvalidRequestError => e
        flash[:error] = e.message
      rescue Stripe::RateLimitError => e
        flash[:error] = e.message
      rescue Stripe::AuthenticationError => e
        flash[:error] = e.message
      rescue Stripe::APIConnectionError => e
        flash[:error] = e.message
      rescue Stripe::StripeError => e
        flash[:error] = e.message
    end
    begin
      charge = Stripe::Charge.create({
        amount: cookies[:amount].present? ? (((cookies[:amount]).to_i * 100).to_i) : (((params[:amount]).to_i * 100).to_i) , # total amount to charge,
        currency: "usd",
        customer: customer.id,
        description: cookies[:campaign].present? ? cookies[:campaign] : 'Basic'
      })
      redirect_to charge_path(:show_confirmation), notice: "Charge was successfully created"
  
      rescue Stripe::CardError => e
        redirect_to request.referer, notice: e.message
      rescue Stripe::InvalidRequestError => e
        redirect_to request.referer, notice: e.message
      rescue Stripe::RateLimitError => e
        redirect_to request.referer, notice: e.message
      rescue Stripe::AuthenticationError => e
        redirect_to request.referer, notice: e.message
      rescue Stripe::APIConnectionError => e
        redirect_to request.referer, notice: e.message
      rescue Stripe::StripeError => e
        redirect_to request.referer, notice: e.message
      rescue => e
        redirect_to request.referer, notice: "Charge Failed"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if request.fullpath == "/"
      cookies.delete :amount
      cookies.delete :campaign
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/King-Kell-fund/_take_amount.html.erb
  <body class="text-center">
  <div class="logo-div">
    <div class="site-logo"><a href="https://dreammachineusa.org/" class="custom-logo-link" rel="home"><img width="1150" height="711" src="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png" class="custom-logo" alt="Dream Machine USA" srcset="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png 1150w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-300x185.png 300w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-1024x633.png 1024w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-768x475.png 768w" sizes="(max-width: 1150px) 100vw, 1150px"></a></div>
  </div>
    <div class="form-signin">
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                    <img class="kingKellPhoto" src="https://www.dreammachineusa.org/wp-content/uploads/2021/09/thumbnail_kingkellphotos-2.jpg" height="450"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section"  style="background: #fff !important;">
                    <h2 class="heading"> Help Musco stay off the streets</h2>
                    <p class="left_align">Your donation will help him find a place to live!</p>
                    <%= form_tag save_amount_path, method: 'post' do %>
                        <input type="text" id="amount" name="amount" class="card-fields" placeholder="Enter Amount"/>
                        <br />
                        <br />
                        <button type="submit" class="donate_button">Continue to Payment</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

<style>
.donate_button{
  text-shadow: none !important;
  background: #EA088C !important;
}

.kingKellPhoto {
  max-height: 560px;
  max-width: 400px;
}
</style>

app/views/charges/King-Kell-fund/_take_card_info.html.erb
  <body class="text-center">
  <div class="logo-div">
    <div class="site-logo"><a href="https://dreammachineusa.org/" class="custom-logo-link" rel="home"><img width="1150" height="711" src="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png" class="custom-logo" alt="Dream Machine USA" srcset="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png 1150w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-300x185.png 300w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-1024x633.png 1024w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-768x475.png 768w" sizes="(max-width: 1150px) 100vw, 1150px"></a></div>
  </div>
    <div class="form-signin">
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                    <img class="kingKellPhoto" src="https://www.dreammachineusa.org/wp-content/uploads/2021/09/thumbnail_kingkellphotos-2.jpg" height="600"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section"  style="background: #fff !important;">
                    <h2 class="heading"> Payment Method</h2>
                    <p class="left_align">Your donation will help King Kell</p>
                    <%= form_tag charges_path, method: 'post', id: 'payment-form' do %>
                        <div class="left_align">
                            <input type="radio" id="credit_or_debit" name="billing_method" value="Credit or Debit" checked="checked">
                            <label for="billing_method">Credit or Debit</label>
                            <br />
                            <input type="text" id="email" name="email" class="card-fields" placeholder="Email"/>
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="first_name" name="first_name" class="card-fields" placeholder="First Name"/>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="last_name" name="last_name" class="card-fields" placeholder="Last Name"/>
                                </div>
                            </div>
                            <br />
                            <input type="text" id="phone" name="phone" class="card-fields" placeholder="Phone"/>
                            <br />
                            <br />
                            <input type="radio" id="billing_name" name="billing_name" value="Use as billing name">
                            <label for="billing_name">Use as billing name</label>
                            <br />
                            <input type="text" id="name" name="name" class="card-fields" placeholder="Name on Card"/>
                            <br />
                            <br />
                            <input type="text" data-stripe="number" class="card-fields" placeholder="Card Number"/>
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-6" style="display: flex;
                                justify-content: center;">
                                    <input style="margin-right: 10px; border-radius: 12px;" type="text" size="4" data-stripe="exp-month" class="card-fields-date" placeholder="MM"/>
                                    <input style="margin-right: 10px; border-radius: 12px;" type="text" data-stripe="cvc" size="4"  placeholder="CVC"/>
                                    <input style="margin-right: 10px; border-radius: 12px;" type="text" size="4" data-stripe="exp-year" class="card-fields-date" placeholder="YYYY"/>
                                </div>
                                <div class="col-md-6">
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <input style="border-radius: 12px;" type="text" id="country" name="country" class="card-fields" placeholder="Country"/>
                                </div>
                                <div class="col-md-6">
                                    <input style="border-radius: 12px;" type="text" id="postal_code" name="postal_code" class="card-fields" placeholder="Postal Code"/>
                                </div>
                            </div>
                            <input type="hidden" id="description" name="description" value="Shelby Compaign"/>
                            <br />
                            <br />
                        </div>
                        <button type="submit" class="donate_button">Donate</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

<style>
.donate_button{
  text-shadow: none !important;
  background: #EA088C !important;
}

form input[type=text]{
    margin-bottom: 10px;
}

.kingKellPhoto {
  max-height: 560px;
  max-width: 400px;
}
</style>

app/views/charges/Lyla-McCarty-fund/_show_confirmation.html.erb
<head>
<title>Thank you!</title>
<link rel="icon" 
      type="image/png" 
      href="https://www.dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png" />
</head>
  <body class="text-center" style="left: 12px; background-image: url(https://www.dreammachineusa.org/wp-content/uploads/2021/10/IMG_7531603456A0-1.jpeg);
  background-size: cover;">
  <div id="fixedHeader" class="" style="display: flex;
  justify-content: center;
  align-items: center;
  position: fixed;
  width: 100vw;
  padding-left: 5%;
  padding-right: 5%;
  top: 0px;
  background: #fff;
  box-shadow: 0px 2px 15px;
  z-index: 100 !important;">
    <a href="https://www.dreammachineusa.org/" class="home_button_container" style="margin-right: 1%;">
     <img class="stickyImg" style=" height: 95px; width: 200px;" src="https://dreammachineusaorg.stage.site/wp-content/uploads/2021/06/the-dream-machine-logo-rectangle-min.png">
    </a>
  </div>

    <div class="form-signin">
  </div>
  <div class="row" style="margin-top: 120px !important;">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                <img src="https://www.dreammachineusa.org/wp-content/uploads/2021/10/Love.png" style="max-height: 360px;" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section"  style="padding-top: 0 !important; background: transparent !important;">
                    <br />
                    <br />
                    <h3 class="heading" style="text-align: center !important; color: #201b58;"> Thank you for your donation, you have just helped a dream come true!</h2>
                    <p class="left_align" style="text-align: center !important; color: #201b58;">Your donation was received.</p>
                    <br />
                    <br />
                    <a href="https://qrstud.io/gcu3ult">
                    <button class="donate_button" style="border: 0;">Download Dreamr</button>
                    </a> 
                    </div>
            </div>
        </div>
    </div>
  </div>
</body>



<style>
.campaignPhoto {
  max-height: 500px;
  max-width: 250px;
}
.kingKellPhoto {
  max-height: 500px;
  max-width: 400px;
  border: solid 6px #EA088C;
  border-right-width: 10px;
  border-radius: 35px 15px 35px 15px;
}
.donate_button{
  color: #fff !important;
  font-size: 1.3rem !important;
  text-shadow: none !important;
  border: 0 !important;
  background: linear-gradient(92deg, #201b58, #020202) !important;

}
.home_button{
  border-radius: 5px;
  border: none;
  font-size: 1.3rem !important;
  text-shadow: none !important;
  background: #95C83E !important;
  height: 60px;
  color: #fff;
}
</style>

app/views/charges/Saras-fund/_take_amount.html.erb
  <body class="text-center">
  <div class="logo-div">
    <div class="site-logo"><a href="https://dreammachineusa.org/" class="custom-logo-link" rel="home"><img width="1150" height="711" src="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png" class="custom-logo" alt="Dream Machine USA" srcset="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png 1150w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-300x185.png 300w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-1024x633.png 1024w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-768x475.png 768w" sizes="(max-width: 1150px) 100vw, 1150px"></a></div>
  </div>
    <div class="form-signin">
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                    <img src="https://images.gofundme.com/NLlPGIuCOn3HN4P7WaZFx3ZjUs8=/1200x900/https://d2g8igdw686xgo.cloudfront.net/58631955_1626910134193243_r.jpeg" height="450"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section">
                    <h2 class="heading"> Help Shelby (Homeless Poet) stay off the streets</h2>
                    <p class="left_align">Your donation will help Shelby</p>
                    <%= form_tag save_amount_path, method: 'post' do %>
                        <input type="text" id="amount" name="amount" class="card-fields" placeholder="Enter Amount"/>
                        <br />
                        <br />
                        <button type="submit" class="donate_button">Continue to Payment</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/charges/Saras-fund/_take_card_info.html.erb
  <body class="text-center">
  <div class="logo-div">
    <div class="site-logo"><a href="https://dreammachineusa.org/" class="custom-logo-link" rel="home"><img width="1150" height="711" src="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png" class="custom-logo" alt="Dream Machine USA" srcset="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png 1150w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-300x185.png 300w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-1024x633.png 1024w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-768x475.png 768w" sizes="(max-width: 1150px) 100vw, 1150px"></a></div>
  </div>
    <div class="form-signin">
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                    <img src="https://images.gofundme.com/NLlPGIuCOn3HN4P7WaZFx3ZjUs8=/1200x900/https://d2g8igdw686xgo.cloudfront.net/58631955_1626910134193243_r.jpeg" height="600"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section">
                    <h2 class="heading"> Payment Method</h2>
                    <p class="left_align">Your donation will help Shelby</p>
                    <%= form_tag charges_path, method: 'post', id: 'payment-form' do %>
                        <div class="left_align">
                            <input type="radio" id="paypal" name="billing_method" value="Paypal">
                            <label for="paypal">Paypal</label>
                            <br />
                            <input type="radio" id="credit_or_debit" name="billing_method" value="Credit or Debit" checked="checked">
                            <label for="billing_method">Credit or Debit</label>
                            <br />
                            <input type="text" id="email" name="email" class="card-fields" placeholder="Email"/>
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="first_name" name="first_name" class="card-fields" placeholder="First Name"/>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="last_name" name="last_name" class="card-fields" placeholder="Last Name"/>
                                </div>
                            </div>
                            <br />
                            <input type="text" id="phone" name="phone" class="card-fields" placeholder="Phone"/>
                            <br />
                            <br />
                            <input type="radio" id="billing_name" name="billing_name" value="Use as billing name">
                            <label for="billing_name">Use as billing name</label>
                            <br />
                            <input type="text" id="name" name="name" class="card-fields" placeholder="Name on Card"/>
                            <br />
                            <br />
                            <input type="text" data-stripe="number" class="card-fields" placeholder="Card Number"/>
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                <label>
                                    <input type="text" size="2" data-stripe="exp-month" class="card-fields-date" placeholder="MM"/>
                                </label>
                                <input type="text" size="4" data-stripe="exp-year" class="card-fields-date" placeholder="YYYY"/>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" data-stripe="cvc" class="card-fields" width="100%" placeholder="CVC"/>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="country" name="country" class="card-fields" placeholder="Country"/>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="postal_code" name="postal_code" class="card-fields" placeholder="Postal Code"/>
                                </div>
                            </div>
                            <input type="hidden" id="description" name="description" value="Shelby Compaign"/>
                            <br />
                            <br />
                        </div>
                        <button type="submit" class="donate_button">Donate</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/charges/Shelbys-fund/_take_amount.html.erb
  <body class="text-center">
  <div class="logo-div">
    <div class="site-logo"><a href="https://dreammachineusa.org/" class="custom-logo-link" rel="home"><img width="1150" height="711" src="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png" class="custom-logo" alt="Dream Machine USA" srcset="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png 1150w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-300x185.png 300w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-1024x633.png 1024w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-768x475.png 768w" sizes="(max-width: 1150px) 100vw, 1150px"></a></div>
  </div>
    <div class="form-signin">
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                    <img src="https://images.gofundme.com/NLlPGIuCOn3HN4P7WaZFx3ZjUs8=/1200x900/https://d2g8igdw686xgo.cloudfront.net/58631955_1626910134193243_r.jpeg" height="450"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section">
                    <h2 class="heading"> Help Shelby (Homeless Poet) stay off the streets</h2>
                    <p class="left_align">Your donation will help Shelby</p>
                    <%= form_tag save_amount_path, method: 'post' do %>
                        <input type="text" id="amount" name="amount" class="card-fields" placeholder="Enter Amount"/>
                        <br />
                        <br />
                        <button type="submit" class="donate_button">Continue to Payment</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/charges/Shelbys-fund/_take_card_info.html.erb
  <body class="text-center">
  <div class="logo-div">
    <div class="site-logo"><a href="https://dreammachineusa.org/" class="custom-logo-link" rel="home"><img width="1150" height="711" src="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png" class="custom-logo" alt="Dream Machine USA" srcset="https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare.png 1150w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-300x185.png 300w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-1024x633.png 1024w, https://dreammachineusa.org/wp-content/uploads/2021/05/cropped-DreamMachineLogoSquare-768x475.png 768w" sizes="(max-width: 1150px) 100vw, 1150px"></a></div>
  </div>
    <div class="form-signin">
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                    <img src="https://images.gofundme.com/NLlPGIuCOn3HN4P7WaZFx3ZjUs8=/1200x900/https://d2g8igdw686xgo.cloudfront.net/58631955_1626910134193243_r.jpeg" height="600"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section">
                    <h2 class="heading"> Payment Method</h2>
                    <p class="left_align">Your donation will help Shelby</p>
                    <%= form_tag charges_path, method: 'post', id: 'payment-form' do %>
                        <div class="left_align">
                            <input type="radio" id="paypal" name="billing_method" value="Paypal">
                            <label for="paypal">Paypal</label>
                            <br />
                            <input type="radio" id="credit_or_debit" name="billing_method" value="Credit or Debit" checked="checked">
                            <label for="billing_method">Credit or Debit</label>
                            <br />
                            <input type="text" id="email" name="email" class="card-fields" placeholder="Email"/>
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="first_name" name="first_name" class="card-fields" placeholder="First Name"/>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="last_name" name="last_name" class="card-fields" placeholder="Last Name"/>
                                </div>
                            </div>
                            <br />
                            <input type="text" id="phone" name="phone" class="card-fields" placeholder="Phone"/>
                            <br />
                            <br />
                            <input type="radio" id="billing_name" name="billing_name" value="Use as billing name">
                            <label for="billing_name">Use as billing name</label>
                            <br />
                            <input type="text" id="name" name="name" class="card-fields" placeholder="Name on Card"/>
                            <br />
                            <br />
                            <input type="text" data-stripe="number" class="card-fields" placeholder="Card Number"/>
                            <br />
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                <label>
                                    <input style="border-radius: 10px !important;" type="text" size="6" data-stripe="exp-month" class="card-fields-date" placeholder="MM"/>
                                </label>
                                <input type="text" size="6" data-stripe="exp-year" class="card-fields-date" placeholder="YYYY"/>
                                </div>
                                <div class="col-md-6">
                                    <input style="border-radius: 10px !important;" size="6" type="text" data-stripe="cvc" class="card-fields" width="100%" placeholder="CVC"/>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="country" name="country" class="card-fields" placeholder="Country"/>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="postal_code" name="postal_code" class="card-fields" placeholder="Postal Code"/>
                                </div>
                            </div>
                            <input type="hidden" id="description" name="description" value="Shelby Compaign"/>
                            <br />
                            <br />
                        </div>
                        <button type="submit" class="donate_button">Donate</button>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/charges/Tony-Rojas-backup-fund/_show_confirmation.html.erb
  <body class="text-center">
  <div id="fixedHeader" class="" style="display: flex;
  justify-content: space-between;
  align-items: center;
  position: fixed;
  width: 100vw;
  padding-left: 5%;
  padding-right: 5%;
  top: 0px;
  background: #ffffff;
  box-shadow: 2px 2px 20px;">
    <img class="stickyImg" style=" height: 95px; width: 200px;" src="https://dreammachineusaorg.stage.site/wp-content/uploads/2021/06/the-dream-machine-logo-rectangle-min.png">
    <a href="https://www.dreammachineusa.org/" class="home_button_container" style="margin-right: 1% !important;">
      <button class="home_button">
      HOME
      </button>
    </a>
  </div>
    <div class="form-signin">
  </div>
  <div class="row" style="margin-top: 120px !important;">
    <div class="col-md-8 offset-md-2">
        <div class="row">
        <div class="col-md-6">
                <div>
                    <img class="kingKellPhoto" src="https://www.dreammachineusa.org/wp-content/uploads/2021/10/Tony-Rojas-Chef-compressed.jpg" height="450"/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="info-section"  style="padding-top: 0 !important; background: #fff !important;">
                    <br />
                    <br />
                    <h3 class="heading" style="text-align: center !important; color: #EA088C;"> Thank you for your donation, you have just helped a dream come true!</h2>
                    <p class="left_align" style="text-align: center !important;">Your donation was received.</p>
                    <br />
                    <br />
                    <a href="https://qrstud.io/gcu3ult">
                    <button class="donate_button" style="border: 0;">Download Dreamr</button>
                    </a> 
                    </div>
            </div>
        </div>
    </div>
  </div>
</body>



<style>
.campaignPhoto {
  max-height: 500px;
  max-width: 250px;
}
.kingKellPhoto {
  max-height: 500px;
  max-width: 400px;
  border: solid 6px #EA088C;
  border-right-width: 10px;
  border-radius: 35px 15px 35px 15px;
}
.donate_button{
  text-shadow: none !important;
  background: #EA088C !important;
}
.home_button{
  border-radius: 5px;
  border: none;
  font-size: 1.3rem !important;
  text-shadow: none !important;
  background: #95C83E !important;
  height: 60px;
  color: #fff;
}
</style>